#!/usr/bin/env python
"""Apply numbered SQL migrations idempotently.

Deliberately not Alembic: the schema is PostGIS-heavy and hand-written DDL with
a checksum ledger is easier to review than autogenerated diffs.
"""
from __future__ import annotations

import hashlib
import sys
from pathlib import Path

import psycopg

from app.config import get_settings

MIGRATIONS = Path(__file__).parent / "migrations"


def main() -> int:
    settings = get_settings()
    files = sorted(MIGRATIONS.glob("*.sql"))
    if not files:
        print("no migrations found", file=sys.stderr)
        return 1

    with psycopg.connect(settings.database_url, autocommit=False) as conn:
        # 001 creates the ledger itself, so bootstrap defensively.
        with conn.cursor() as cur:
            cur.execute(
                "SELECT EXISTS (SELECT 1 FROM information_schema.tables "
                "WHERE table_name = 'schema_migrations')"
            )
            has_ledger = cur.fetchone()[0]
            applied: dict[str, str] = {}
            if has_ledger:
                cur.execute("SELECT filename, checksum FROM schema_migrations")
                applied = dict(cur.fetchall())
        conn.commit()

        for path in files:
            sql = path.read_text()
            checksum = hashlib.sha256(sql.encode()).hexdigest()[:16]
            prev = applied.get(path.name)
            if prev == checksum:
                print(f"  = {path.name} (already applied)")
                continue
            if prev and prev != checksum:
                print(
                    f"  ! {path.name} changed after being applied "
                    f"({prev} -> {checksum}); re-running (DDL is idempotent)"
                )
            print(f"  + {path.name}")
            with conn.cursor() as cur:
                cur.execute(sql)
                cur.execute(
                    "INSERT INTO schema_migrations (filename, checksum) VALUES (%s,%s) "
                    "ON CONFLICT (filename) DO UPDATE SET checksum = EXCLUDED.checksum, "
                    "applied_at = now()",
                    (path.name, checksum),
                )
            conn.commit()

    print("migrations complete")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
