"""PostgreSQL/PostGIS access via a psycopg3 connection pool.

Geospatial queries are written as explicit SQL rather than being generated by
an ORM: PostGIS predicates and window functions are the performance-critical
part of this application and hand-written SQL keeps the query plans legible.
"""
from __future__ import annotations

import logging
from collections.abc import Iterator, Sequence
from contextlib import asynccontextmanager, contextmanager
from typing import Any

from psycopg.rows import dict_row
from psycopg_pool import AsyncConnectionPool, ConnectionPool

from .config import get_settings

log = logging.getLogger(__name__)

_async_pool: AsyncConnectionPool | None = None
_sync_pool: ConnectionPool | None = None


def _conninfo() -> str:
    return get_settings().database_url


async def open_async_pool() -> AsyncConnectionPool:
    global _async_pool
    if _async_pool is None:
        s = get_settings()
        _async_pool = AsyncConnectionPool(
            _conninfo(),
            min_size=s.db_pool_min,
            max_size=s.db_pool_max,
            open=False,
            # Validate a connection before handing it out. Without this the
            # pool keeps serving sockets that died when PostgreSQL restarted,
            # and every request fails with "server closed the connection
            # unexpectedly" until the pool happens to recycle them. A restart
            # of the database should be invisible to the API.
            check=AsyncConnectionPool.check_connection,
            # Recycle idle connections so a long-lived process does not hold
            # sockets open indefinitely.
            max_idle=300,
            reconnect_timeout=30,
            kwargs={
                "row_factory": dict_row,
                "options": f"-c statement_timeout={s.db_statement_timeout_ms}",
            },
        )
        await _async_pool.open(wait=True, timeout=30)
        log.info("database pool opened (min=%s max=%s)", s.db_pool_min, s.db_pool_max)
    return _async_pool


async def close_async_pool() -> None:
    global _async_pool
    if _async_pool is not None:
        await _async_pool.close()
        _async_pool = None


@asynccontextmanager
async def acquire():
    """Yield an async connection from the pool."""
    pool = await open_async_pool()
    async with pool.connection() as conn:
        yield conn


async def fetch_all(sql: str, params: Sequence[Any] | dict | None = None) -> list[dict]:
    async with acquire() as conn, conn.cursor() as cur:
        await cur.execute(sql, params)
        return await cur.fetchall()


async def fetch_one(sql: str, params: Sequence[Any] | dict | None = None) -> dict | None:
    async with acquire() as conn, conn.cursor() as cur:
        await cur.execute(sql, params)
        return await cur.fetchone()


async def fetch_val(sql: str, params: Sequence[Any] | dict | None = None) -> Any:
    row = await fetch_one(sql, params)
    if not row:
        return None
    return next(iter(row.values()))


async def execute(sql: str, params: Sequence[Any] | dict | None = None) -> None:
    async with acquire() as conn, conn.cursor() as cur:
        await cur.execute(sql, params)


# --- synchronous access, used by ingestion and ML scripts -------------------


def sync_pool() -> ConnectionPool:
    global _sync_pool
    if _sync_pool is None:
        _sync_pool = ConnectionPool(
            _conninfo(), min_size=1, max_size=4, open=True,
            check=ConnectionPool.check_connection,
            kwargs={"row_factory": dict_row},
        )
    return _sync_pool


@contextmanager
def sync_conn() -> Iterator[Any]:
    with sync_pool().connection() as conn:
        yield conn


def sync_fetch_all(sql: str, params: Sequence[Any] | dict | None = None) -> list[dict]:
    with sync_conn() as conn, conn.cursor() as cur:
        cur.execute(sql, params)
        return cur.fetchall()


def sync_fetch_one(sql: str, params: Sequence[Any] | dict | None = None) -> dict | None:
    with sync_conn() as conn, conn.cursor() as cur:
        cur.execute(sql, params)
        return cur.fetchone()
